### ISSUE TITLE
大佬，能不能也把mac版编译一下

### ISSUE THREAD

**Issue by champkeh** [Sec-ant/anti-anti-debugging-debugger-firefox#3]

**Comment by Sec-ant** [comment]
我没有 macOS 设备和使用经验，所以我不确定能不能成功。你如果自己有设备的话可以先参考 FireFox 的官方编译指南：https://firefox-source-docs.mozilla.org/setup/macos_build.html 和这个仓库里 Linux 的编译 workflow：https://github.com/Sec-ant/a2d2-firefox/blob/main/.github/workflows/build-on-linux.yml ，试试自己能不能在本地编译成功。

**Comment by champkeh** [comment]
好的，我先试试

**Comment by Sec-ant** [comment]
@champkeh 我编译了一个 macOS 版本的，方便的话请帮我测试一下能否正常安装使用以及 `debugger` 关键字是否替换成功？

https://github.com/Sec-ant/a2d2-firefox/releases/tag/macos-20230907135455

**Comment by champkeh** [comment]
可以运行，并且debugger关键字也成功被替换了
<img width="899" alt="image" src="https://github.com/Sec-ant/a2d2-firefox/assets/7316006/6dc3292a-4cab-4e2a-8cab-e844b0d533ca">

系统信息：
Apple M1 Pro
macOS Sonoma Version 14.0 Beta

感谢大佬👍
